<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-4MLC4R0" ignored="0" name="Test Maven Testing" tests="12" failures="6" timestamp="2022-05-07T22:09:23 IST" time="0.176" errors="0">
  <testcase name="div" time="0.015" classname="com.qa.tests.Demo">
    <failure type="java.lang.AssertionError" message="expected [0] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [30]
at com.qa.tests.Demo.div(Demo.java:36)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="mul" time="0.003" classname="com.qa.tests.Demo">
    <failure type="java.lang.AssertionError" message="expected [200] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [30]
at com.qa.tests.Demo.mul(Demo.java:28)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- mul -->
  <testcase name="sub" time="0.004" classname="com.qa.tests.Demo">
    <failure type="java.lang.AssertionError" message="expected [-10] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [-10] but found [30]
at com.qa.tests.Demo.sub(Demo.java:20)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sum" time="0.006" classname="com.qa.tests.Demo"/>
  <testcase name="div" time="0.001" classname="com.qa.tests.DemoSample"/>
  <testcase name="mul" time="0.001" classname="com.qa.tests.DemoSample"/>
  <testcase name="sub" time="0.003" classname="com.qa.tests.DemoSample"/>
  <testcase name="sum" time="0.0" classname="com.qa.tests.DemoSample"/>
  <testcase name="div" time="0.001" classname="com.qa.tests.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [30]
at com.qa.tests.DemoTest.div(DemoTest.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="mul" time="0.001" classname="com.qa.tests.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [200] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [30]
at com.qa.tests.DemoTest.mul(DemoTest.java:29)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- mul -->
  <testcase name="sub" time="0.001" classname="com.qa.tests.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [-10] but found [30]">
      <![CDATA[java.lang.AssertionError: expected [-10] but found [30]
at com.qa.tests.DemoTest.sub(DemoTest.java:21)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- sub -->
  <testcase name="sum" time="0.0" classname="com.qa.tests.DemoTest"/>
</testsuite> <!-- Test Maven Testing -->
